New branch for PM task
daniel-jodlos/gmm-indexer-erlang pull request #1
Opened 2021-05-06 14:55 UTC by MrPaulMarshall

No to pierwszy pull request już jest

2021-05-07 17:02 UTC, lopiola requested changes

2021-05-07 17:02 UTC, lopiola commented on src/gmm_handler.erl
> +  case string:to_integer(String) of
nie trzeba tak na okrętkę, `binary_to_integer`

2021-05-07 17:02 UTC, lopiola commented on src/gmm_sup.erl
> +    ets:insert(#state{}#state.table, {next_id, 0}),
nietypowo używasz rekordu, bo zrobiłeś sobie z niego opakowanie na pewną stałą i wyciągasz ją w dziwaczny sposób

lepiej po prostu zrobić
`-define(USERS_TABLE, users_table)` i używać sobie makra `ets:insert(?USERS_TABLE, {next_id, 0}),`

2021-05-07 17:49 UTC, MrPaulMarshall commented on src/gmm_handler.erl
> +  ets:update_element(State#state.table, next_id, {2, Id+1}),
Hmm... jest to pozostałość z wprawki w pierwszym tygodniu, ale jak najbardziej ma to sens. Natomiast mam pytanie: czy mogę założyć unikalność tego i już? Tzn. szanse na powtórzenie są astronomicznie małe, ale niezerowe - co w przypadku konfliktu?

2021-05-07 17:49 UTC, MrPaulMarshall commented on src/gmm_handler.erl
> +    [{_, Name} | _] -> jiffy:encode({[{<<"id">>, Id}, {<<"name">>, binary:list_to_bin(Name)}]})
Ok, nie ma problemu

2021-05-07 18:48 UTC, lopiola commented on src/gmm_handler.erl
> +  ets:update_element(State#state.table, next_id, {2, Id+1}),
Można po prostu założyć, że będą unikalne. Generalnie nie zaszkodziłoby przegenerowanie idka jeszcze raz jakby baza zwróciła, że taki już istnieje, ale szansa jest niezwykle mała - więc możemy sobie darować.

2021-05-07 20:09 UTC, MrPaulMarshall commented on src/gmm_handler.erl
> +-export([
Zrobione

2021-05-07 20:12 UTC, MrPaulMarshall commented on src/gmm_handler.erl
> +  jiffy:encode({[]}).
Jest problem kiedy chcę zakodować jsona który ma więcej niż jedno pole

{[ #{<<"id">> => Id}, #{<<"name">> => Name} ]}
wywala błąd. kilka innych kombinacji co próbowałem również. jak to zrobić?

2021-05-07 20:12 UTC, MrPaulMarshall commented on src/gmm_handler.erl
> +  List = lists:map(fun({Id, _}) -> Id end, UsersList),
Dzięki

2021-05-07 20:15 UTC, MrPaulMarshall commented on src/gmm_app.erl
>          #{env => #{dispatch => Dispatch}}
Zrobione

2021-05-07 20:26 UTC, MrPaulMarshall commented on src/gmm_handler.erl
> +bin_to_num(Bin) ->
Zrobione

2021-05-07 20:34 UTC, MrPaulMarshall commented on src/gmm_sup.erl
> +    ets:insert(#state{}#state.table, {next_id, 0}),
Tymczasem poprawione

2021-05-07 20:50 UTC, MrPaulMarshall commented on src/gmm_handler.erl
> +  ets:update_element(State#state.table, next_id, {2, Id+1}),
Skończone

2021-05-08 08:59 UTC, MrPaulMarshall commented on src/gmm_handler.erl
> +  jiffy:encode({[]}).
Ostatnia rzecz zrobiona

2021-05-08 09:31 UTC, closed without merging