GMMIN-18-permissions-logic
daniel-jodlos/gmm-indexer-erlang pull request #11
Opened 2021-05-23 18:04 UTC by daniel-jodlos

Zawiera:
- implementację zdefiniowanego API do operacji na krawędziach
- zmianę konwencji nazewnictwa z {Parent, Child} na {To, From}, jako dostosowanie się do kodu Kamila. W liczbie mnogiej oczywiście nadal pozostaje {Parents, Children}

2021-05-23 18:15 UTC, MrPaulMarshall requested changes
Ogólnie spoko. W miarę tego jak będę implementował restowe api mogą się okazać dalsze zmiany w nazewnictwie, ale to się okaże. Natomiast BARDZO ISTOTNE: napisz w widocznym miejscu modułu graph.erl jak się mają From, To do Parent, Child, bo to jest strasznie nieoczywiste i może powodować bugi.

2021-05-24 05:31 UTC, daniel-jodlos commented
@MrPaulMarshall O coś takiego chodziło? Jeżeli nie o to, to może lepiej sam to już dopisz

2021-05-24 06:55 UTC, MrPaulMarshall commented
> @MrPaulMarshall O coś takiego chodziło? Jeżeli nie o to, to może lepiej sam to już dopisz

Chodziło mi o mapę postaci:
{From <-> Parent, To <-> Child}

Albo
{From <-> Child, To <-> Parent}

2021-05-24 07:28 UTC, daniel-jodlos commented
> > @MrPaulMarshall O coś takiego chodziło? Jeżeli nie o to, to może lepiej sam to już dopisz
> 
> Chodziło mi o mapę postaci:
> {From <-> Parent, To <-> Child}
> 
> Albo
> {From <-> Child, To <-> Parent}

Takiej mapy na pewno nikt nie zrozumie, tak szczerze mówiąc. Myślę że lepiej by było to dopisać po prostu słownie

2021-05-24 07:35 UTC, MrPaulMarshall commented
> > > @MrPaulMarshall O coś takiego chodziło? Jeżeli nie o to, to może lepiej sam to już dopisz
> > 
> > 
> > Chodziło mi o mapę postaci:
> > {From <-> Parent, To <-> Child}
> > Albo
> > {From <-> Child, To <-> Parent}
> 
> Takiej mapy na pewno nikt nie zrozumie, tak szczerze mówiąc. Myślę że lepiej by było to dopisać po prostu słownie

Być może masz rację, ale w zamyśle o to chodzi, dwa zdania: "From jest równoważny X", "To jest równoważne Y"

2021-05-24 08:36 UTC, MrPaulMarshall approved these changes

2021-05-24 09:22 UTC, merged