GMMIN-39 fix ci to use ct tests
daniel-jodlos/gmm-indexer-erlang pull request #25
Opened 2021-06-16 11:35 UTC by awojciak

2021-06-18 06:35 UTC, daniel-jodlos commented
Według mnie CT powinno należeć do joba test. Ewentualnie można by zrobić joby `unit_tests` i `integration_tests` i chyba ten drugi powinien wymagać zdania pierwszych

2021-06-21 09:16 UTC, MrPaulMarshall approved these changes
Wygląda legitnie, jak działa to merguj

2021-06-21 10:42 UTC, daniel-jodlos requested changes

2021-06-21 10:42 UTC, daniel-jodlos commented on .github/workflows/erlang.yml
> +jobs:
Usuńmy może tego taba

2021-06-21 10:42 UTC, daniel-jodlos commented on .github/workflows/erlang.yml
> +        OTP_VERSION="23.2.3-1"
Podbij wersję erlanga do 24.x.x, chyba wszyscy mają taką zainstalowaną na kompach

2021-06-21 14:15 UTC, awojciak commented on .github/workflows/erlang.yml
> +jobs:
już

2021-06-21 14:15 UTC, awojciak commented on .github/workflows/erlang.yml
> +        OTP_VERSION="23.2.3-1"
już

2021-06-21 14:34 UTC, MrPaulMarshall approved these changes
Merguj

2021-06-21 16:04 UTC, daniel-jodlos approved these changes
Zmergujmy to ze squashem

2021-06-21 16:06 UTC, merged