Gmmin 9 persistence for gmm server
daniel-jodlos/gmm-indexer-erlang pull request #5
Opened 2021-05-11 15:41 UTC by awojciak

2021-05-11 16:00 UTC, daniel-jodlos requested changes
W sumie dobra robota. Największe zastrzeżenie to to, że proces obsługujący persystencję nie należy do drzewka nadzoru

2021-05-11 16:39 UTC, MrPaulMarshall commented on src/persistence.erl
> +    {ok, RedisClient}.
No chyba, że chcemy żeby wywaliło ewentualny błąd na tym etapie. Jeśli nie, to można to uprościć

2021-05-11 16:40 UTC, MrPaulMarshall commented on src/persistence.erl
> +    gen_server:call(ServerName, {keys, Pattern}).
Tak, lepiej by było żeby interfejs mówił tylko jakie operacje udostępnia, a nie co się za tym kryje

2021-05-11 16:41 UTC, MrPaulMarshall commented on src/persistence.erl
> +-export([get_user/2, get_users/1, add_user/2, delete_user/2, update_user/3]).
Eksporty wyglądają w porządku

2021-05-11 16:48 UTC, daniel-jodlos commented on src/persistence.erl
> +-export([get_user/2, get_users/1, add_user/2, delete_user/2, update_user/3]).
Są w porządku. Ale u Piotra są w różnicy linijkach, w mainie też. Kwestia jednolitości, nic więcej

2021-05-12 08:09 UTC, awojciak commented on src/gmm_sup.erl
> +    persistence:start_link(?REDIS_SERVER),
przeniesiony

2021-05-12 08:09 UTC, awojciak commented on src/persistence.erl
> +-export([get_user/2, get_users/1, add_user/2, delete_user/2, update_user/3]).
poprawione

2021-05-12 08:09 UTC, awojciak commented on src/persistence.erl
> +    {ok, RedisClient}.
wywalone

2021-05-12 08:09 UTC, awojciak commented on src/persistence.erl
> +    gen_server:call(ServerName, {keys, Pattern}).
poprawione

2021-05-12 08:36 UTC, daniel-jodlos approved these changes

2021-05-12 09:08 UTC, MrPaulMarshall reviewed
Może być

2021-05-12 10:55 UTC, merged