Gmmin 15 persistent membership index
daniel-jodlos/gmm-indexer-erlang pull request #6
Opened 2021-05-18 07:20 UTC by daniel-jodlos

2021-05-18 08:55 UTC, MrPaulMarshall requested changes
Ogólnie wygląda ok, ale nie widzę w ogóle w pliku graph.erl funkcji do tworzenia i usuwania grup.

Oprócz tego trzeba by już od razu to zrefaktoryzować tak, żeby dało się potem łatwo dodać inne typy wierzchołków: grupy (w końcu grupa może być dzieckiem innej grupy) oraz zasoby.
Czyli zrobić tak, żeby podstawową jednostką był {Node}, a to czy jest to user, group czy resource to może być już określane przez pole #{<<"type">> => <<"value">>}

PS.
PILNE: dołożyć obustronne powiązanie między rodzicami a dziećmi (aka, żeby dzieci miały info o swoich rodzicach), bo na razie wierzchołki mają tylko id-ki swoich dzieci

2021-05-18 10:28 UTC, awojciak commented
Kod z commita jest ok, ale twoje zmiany trzeba uwzględnić też w innych plikach, które używają tych funkcji, np. gmm_rest_handler.erl. Sugestia Pawła też wydaje mi się słuszna.

2021-05-18 10:29 UTC, awojciak requested changes
Kod z commita jest ok, ale twoje zmiany trzeba uwzględnić też w innych plikach, które używają tych funkcji, np. gmm_rest_handler.erl, wiec przejrzyj jeszcze projekt. Sugestia Pawła też wydaje mi się słuszna.

2021-05-18 11:43 UTC, daniel-jodlos commented
Odnosząc się do:

> Oprócz tego trzeba by już od razu to zrefaktoryzować tak, żeby dało się potem łatwo dodać inne typy wierzchołków: grupy (w końcu grupa może być dzieckiem innej grupy) oraz zasoby.

Kod nie zakłada żadnego typu wierzchołka, jest to tylko kwestia nazewnictwa funkcji. Natomiast wprowadzenie innych typów to zadanie `GMMIN-13 Implement group, space, provider models`.

2021-05-18 11:44 UTC, daniel-jodlos commented
> Kod z commita jest ok, ale twoje zmiany trzeba uwzględnić też w innych plikach, które używają tych funkcji, np. gmm_rest_handler.erl, wiec przejrzyj jeszcze projekt. Sugestia Pawła też wydaje mi się słuszna.

Ok, good point. Pytanie tylko dlaczego w takim razie nie wywaliło ani testów

2021-05-18 12:11 UTC, MrPaulMarshall commented
> Odnosząc się do:
> 
> > Oprócz tego trzeba by już od razu to zrefaktoryzować tak, żeby dało się potem łatwo dodać inne typy wierzchołków: grupy (w końcu grupa może być dzieckiem innej grupy) oraz zasoby.
> 
> Kod nie zakłada żadnego typu wierzchołka, jest to tylko kwestia nazewnictwa funkcji.
> 
> > Ogólnie wygląda ok, ale nie widzę w ogóle w pliku graph.erl funkcji do tworzenia i usuwania grup.
> 
> Wprowadzenie innych typów to zadanie `GMMIN-13 Implement group, space, provider models`.

Racja, natomiast to nazewnictwo trzeba by poprawić, albo dodać analogiczne dla grup i zasobów

2021-05-18 12:12 UTC, MrPaulMarshall commented
> > Kod z commita jest ok, ale twoje zmiany trzeba uwzględnić też w innych plikach, które używają tych funkcji, np. gmm_rest_handler.erl, wiec przejrzyj jeszcze projekt. Sugestia Pawła też wydaje mi się słuszna.
> 
> Ok, good point. Pytanie tylko dlaczego w takim razie nie wywaliło testów

Nie wiem. Był tam użyty persistence:fun(?REDIS_SERVER, Variable), tak więc nie zgadzała się ilość argumentów z tym co moduł persistent deklarował

2021-05-19 22:14 UTC, awojciak approved these changes
kod jest ok, sugestia Pawła będzie realizowana w innym pr, daje okejkę

2021-05-20 05:47 UTC, MrPaulMarshall approved these changes
Podobnie jak Adrian, daję ok

2021-05-23 17:05 UTC, daniel-jodlos commented
Zamknięty z powodu przeniesienia kodu w inne miejsce przez inny Pull Request

2021-05-23 17:05 UTC, closed without merging